version: "3.6"
services:
  flextesa:
    container_name: my_flextesa
    restart: always
    image: oxheadalpha/flextesa:20230607
    command: nairobibox start
    environment:
      - block_time=4
      - flextesa_node_cors_origin=*
    ports:
      - 127.0.0.1:20000:20000
    expose:
      - 20000/tcp
